-- MySQL Script generated by MySQL Workbench
-- 11/13/17 10:46:23
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema citationdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `citationdb` ;

-- -----------------------------------------------------
-- Schema citationdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `citationdb` DEFAULT CHARACTER SET utf8 ;
USE `citationdb` ;

-- -----------------------------------------------------
-- Table `citationdb`.`citation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `citationdb`.`citation` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `quote` VARCHAR(255) NOT NULL,
  `author` VARCHAR(255) NOT NULL,
  `topic` VARCHAR(50) NOT NULL,
  `updated` DATETIME NULL,
  `created` DATETIME NULL,
  `birthdate` DATE NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `quote_UNIQUE` (`quote` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `citationdb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `citationdb`.`user` (
  `iduser` INT NOT NULL,
  `name` VARCHAR(50) NULL,
  `surname` VARCHAR(50) NULL,
  `username` VARCHAR(50) NULL,
  `email` VARCHAR(50) NULL,
  PRIMARY KEY (`iduser`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `citationdb`.`background`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `citationdb`.`background` (
  `idbackground` INT NOT NULL AUTO_INCREMENT,
  `backgroundblob` BLOB NOT NULL,
  PRIMARY KEY (`idbackground`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `citationdb`.`citation`
-- -----------------------------------------------------
START TRANSACTION;
USE `citationdb`;
INSERT INTO `citationdb`.`citation` (`ID`, `quote`, `author`, `topic`, `updated`, `created`, `birthdate`) VALUES (1, 'So etwas wie moralische oder unmoralische Bücher gibt es nicht. Bücher sind gut oder schlecht geschrieben. Weiter nichts.', 'Oscar Wilde', 'Bücher', NULL, NULL, NULL);
INSERT INTO `citationdb`.`citation` (`ID`, `quote`, `author`, `topic`, `updated`, `created`, `birthdate`) VALUES (2, 'Ein Haus ohne Bücher ist arm, auch wenn schöne Teppiche seinen Böden und kostbare Tapeten und Bilder die Wände bedecken.', 'Hermann Hesse', DEFAULT, NULL, NULL, NULL);
INSERT INTO `citationdb`.`citation` (`ID`, `quote`, `author`, `topic`, `updated`, `created`, `birthdate`) VALUES (3, DEFAULT, DEFAULT, DEFAULT, NULL, NULL, NULL);
INSERT INTO `citationdb`.`citation` (`ID`, `quote`, `author`, `topic`, `updated`, `created`, `birthdate`) VALUES (4, DEFAULT, DEFAULT, DEFAULT, NULL, NULL, NULL);
INSERT INTO `citationdb`.`citation` (`ID`, `quote`, `author`, `topic`, `updated`, `created`, `birthdate`) VALUES (5, DEFAULT, DEFAULT, DEFAULT, NULL, NULL, NULL);
INSERT INTO `citationdb`.`citation` (`ID`, `quote`, `author`, `topic`, `updated`, `created`, `birthdate`) VALUES (6, DEFAULT, DEFAULT, DEFAULT, NULL, NULL, NULL);
INSERT INTO `citationdb`.`citation` (`ID`, `quote`, `author`, `topic`, `updated`, `created`, `birthdate`) VALUES (7, DEFAULT, DEFAULT, DEFAULT, NULL, NULL, NULL);
INSERT INTO `citationdb`.`citation` (`ID`, `quote`, `author`, `topic`, `updated`, `created`, `birthdate`) VALUES (8, DEFAULT, DEFAULT, DEFAULT, NULL, NULL, NULL);
INSERT INTO `citationdb`.`citation` (`ID`, `quote`, `author`, `topic`, `updated`, `created`, `birthdate`) VALUES (9, DEFAULT, DEFAULT, DEFAULT, NULL, NULL, NULL);
INSERT INTO `citationdb`.`citation` (`ID`, `quote`, `author`, `topic`, `updated`, `created`, `birthdate`) VALUES (10, DEFAULT, DEFAULT, DEFAULT, NULL, NULL, NULL);
INSERT INTO `citationdb`.`citation` (`ID`, `quote`, `author`, `topic`, `updated`, `created`, `birthdate`) VALUES (11, DEFAULT, DEFAULT, DEFAULT, NULL, NULL, NULL);
INSERT INTO `citationdb`.`citation` (`ID`, `quote`, `author`, `topic`, `updated`, `created`, `birthdate`) VALUES (12, DEFAULT, DEFAULT, DEFAULT, NULL, NULL, NULL);
INSERT INTO `citationdb`.`citation` (`ID`, `quote`, `author`, `topic`, `updated`, `created`, `birthdate`) VALUES (13, DEFAULT, DEFAULT, DEFAULT, NULL, NULL, NULL);

COMMIT;

