-- MySQL Script generated by MySQL Workbench
-- 12/04/17 09:22:32
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema citationdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `citationdb` ;

-- -----------------------------------------------------
-- Schema citationdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `citationdb` DEFAULT CHARACTER SET utf8 ;
USE `citationdb` ;

-- -----------------------------------------------------
-- Table `citationdb`.`author`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `citationdb`.`author` (
  `idauthor` INT NOT NULL,
  `aname` VARCHAR(50) NULL,
  `abirthdate` DATE NULL,
  `deathdate` DATE NULL,
  `biography` VARCHAR(250) NULL,
  PRIMARY KEY (`idauthor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `citationdb`.`citation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `citationdb`.`citation` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `quote` VARCHAR(255) NOT NULL,
  `topic` VARCHAR(50) NOT NULL,
  `updated` DATETIME NULL,
  `created` DATETIME NULL,
  `author_idauthor` INT NOT NULL,
  `like` INT NULL DEFAULT 0,
  `hit` INT NULL DEFAULT 0,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `quote_UNIQUE` (`quote` ASC),
  INDEX `fk_citation_author_idx` (`author_idauthor` ASC),
  CONSTRAINT `fk_citation_author`
    FOREIGN KEY (`author_idauthor`)
    REFERENCES `citationdb`.`author` (`idauthor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `citationdb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `citationdb`.`user` (
  `iduser` INT NOT NULL,
  `name` VARCHAR(50) NULL,
  `surname` VARCHAR(50) NULL,
  `username` VARCHAR(50) NOT NULL,
  `email` VARCHAR(50) NULL,
  `password` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`iduser`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `citationdb`.`background`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `citationdb`.`background` (
  `idbackground` INT NOT NULL AUTO_INCREMENT,
  `backgroundblob` BLOB NOT NULL,
  PRIMARY KEY (`idbackground`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `citationdb`.`author`
-- -----------------------------------------------------
START TRANSACTION;
USE `citationdb`;
INSERT INTO `citationdb`.`author` (`idauthor`, `aname`, `abirthdate`, `deathdate`, `biography`) VALUES (1, 'Oscar Wilde', '1854-10-16', '1900-11-30', NULL);
INSERT INTO `citationdb`.`author` (`idauthor`, `aname`, `abirthdate`, `deathdate`, `biography`) VALUES (2, 'Hermann Hesse', '1877-07-02', '1962-08-09', NULL);
INSERT INTO `citationdb`.`author` (`idauthor`, `aname`, `abirthdate`, `deathdate`, `biography`) VALUES (3, 'Marie von Ebner-Eschenbach', '1830-09-13', '1916-03-12', NULL);
INSERT INTO `citationdb`.`author` (`idauthor`, `aname`, `abirthdate`, `deathdate`, `biography`) VALUES (4, 'Albert Einstein', '1879-03-14', '1955-04-18', NULL);
INSERT INTO `citationdb`.`author` (`idauthor`, `aname`, `abirthdate`, `deathdate`, `biography`) VALUES (5, 'Aristoteles', '-384', '-322', NULL);
INSERT INTO `citationdb`.`author` (`idauthor`, `aname`, `abirthdate`, `deathdate`, `biography`) VALUES (6, 'Françoise Sagan', '1935-07-21', '2004-09-24', NULL);
INSERT INTO `citationdb`.`author` (`idauthor`, `aname`, `abirthdate`, `deathdate`, `biography`) VALUES (7, 'J.R.R Tolkien', '1892-01-03', '1973-09-02', NULL);
INSERT INTO `citationdb`.`author` (`idauthor`, `aname`, `abirthdate`, `deathdate`, `biography`) VALUES (8, 'Jeanne Moreau', '1928-01-23', '2017-07-31', NULL);
INSERT INTO `citationdb`.`author` (`idauthor`, `aname`, `abirthdate`, `deathdate`, `biography`) VALUES (9, 'Charles Dickens', '1812-02-07', '1870-06-09', NULL);
INSERT INTO `citationdb`.`author` (`idauthor`, `aname`, `abirthdate`, `deathdate`, `biography`) VALUES (10, 'Woody Allen', '1935-12-01', '', NULL);
INSERT INTO `citationdb`.`author` (`idauthor`, `aname`, `abirthdate`, `deathdate`, `biography`) VALUES (11, 'Sigismund von Radecki', '1891-11-19', '1970-03-13', NULL);

COMMIT;


-- -----------------------------------------------------
-- Data for table `citationdb`.`citation`
-- -----------------------------------------------------
START TRANSACTION;
USE `citationdb`;
INSERT INTO `citationdb`.`citation` (`ID`, `quote`, `topic`, `updated`, `created`, `author_idauthor`, `like`, `hit`) VALUES (1, 'So etwas wie moralische oder unmoralische Bücher gibt es nicht. Bücher sind gut oder schlecht geschrieben. Weiter nichts.', 'Bücher', NULL, NULL, 1, NULL, NULL);
INSERT INTO `citationdb`.`citation` (`ID`, `quote`, `topic`, `updated`, `created`, `author_idauthor`, `like`, `hit`) VALUES (2, 'Ein Haus ohne Bücher ist arm, auch wenn schöne Teppiche seinen Böden und kostbare Tapeten und Bilder die Wände bedecken.', 'Bücher', NULL, NULL, 2, NULL, NULL);
INSERT INTO `citationdb`.`citation` (`ID`, `quote`, `topic`, `updated`, `created`, `author_idauthor`, `like`, `hit`) VALUES (3, 'Über das Kommen mancher Leute tröstet uns nichts als die Hoffnung auf ihr Gehen.', 'Hoffnung', NULL, NULL, 3, NULL, NULL);
INSERT INTO `citationdb`.`citation` (`ID`, `quote`, `topic`, `updated`, `created`, `author_idauthor`, `like`, `hit`) VALUES (4, 'Zeit ist das, was man an der Uhr abliest.', 'Zeit', NULL, NULL, 4, NULL, NULL);
INSERT INTO `citationdb`.`citation` (`ID`, `quote`, `topic`, `updated`, `created`, `author_idauthor`, `like`, `hit`) VALUES (5, 'Freundschaft, das ist eine Seele in zwei Körpern.', 'Freundschaft', NULL, NULL, 5, NULL, NULL);
INSERT INTO `citationdb`.`citation` (`ID`, `quote`, `topic`, `updated`, `created`, `author_idauthor`, `like`, `hit`) VALUES (6, 'Man weiss selten, was Glück ist, aber man weiss meistens was Glück war.', 'Glück', NULL, NULL, 6, NULL, NULL);
INSERT INTO `citationdb`.`citation` (`ID`, `quote`, `topic`, `updated`, `created`, `author_idauthor`, `like`, `hit`) VALUES (7, 'Derjenige, der etwas zerbricht, um herauszufinden, was es ist, hat den Pfad der Weisheit verlassen.', 'Weisheiten', NULL, NULL, 7, NULL, NULL);
INSERT INTO `citationdb`.`citation` (`ID`, `quote`, `topic`, `updated`, `created`, `author_idauthor`, `like`, `hit`) VALUES (8, 'Weisheit stellt sich nicht immer mit dem Alter ein. Manchmal kommt auch das Alter ganz allein.', 'Weisheiten', NULL, NULL, 8, NULL, NULL);
INSERT INTO `citationdb`.`citation` (`ID`, `quote`, `topic`, `updated`, `created`, `author_idauthor`, `like`, `hit`) VALUES (9, 'Der Humor nimmt die Welt hin, wie sie ist, sucht sie nicht zu verbessern und zu belehren, sondern mit Weisheit zu ertragen.', 'Weisheiten', NULL, NULL, 9, NULL, NULL);
INSERT INTO `citationdb`.`citation` (`ID`, `quote`, `topic`, `updated`, `created`, `author_idauthor`, `like`, `hit`) VALUES (10, 'Sex ist nur schmutzig, wenn er richtig gemacht wird.', 'Sex', NULL, NULL, 10, NULL, NULL);
INSERT INTO `citationdb`.`citation` (`ID`, `quote`, `topic`, `updated`, `created`, `author_idauthor`, `like`, `hit`) VALUES (11, 'Aller Humor fängt damit an, dass man die eigene Person nicht mehr ernst nimmt.', 'Humor', NULL, NULL, 2, NULL, NULL);
INSERT INTO `citationdb`.`citation` (`ID`, `quote`, `topic`, `updated`, `created`, `author_idauthor`, `like`, `hit`) VALUES (12, 'Deutscher Humor ist, wenn man trotzdem nicht lacht', 'Humor', NULL, NULL, 11, NULL, NULL);
INSERT INTO `citationdb`.`citation` (`ID`, `quote`, `topic`, `updated`, `created`, `author_idauthor`, `like`, `hit`) VALUES (13, 'Als ich klein war, glaubte ich, Geld sei das wichtigste im Leben. Heute, da ich alt bin, weiß ich: Es stimmt.', 'Geld', NULL, NULL, 1, NULL, NULL);

COMMIT;

